### PR TITLE
moving QuadratureRule over to an equinox.Module and patched up a few …

### PR DESCRIPTION
**Pull request by cmhamel**
…tests that was using the old QuadratureRule.len method. Now using a __len__ method in QuadratureRule so we can use the python built-in len method.

### CODE REVIEW

**Comment by cmhamel** [comment]
@btalamini You suggested splitting up PR #87 since @ralberd was seeing some performance regressions from that initial stab I took which likely changed too much too fast.

This PR does something simple. Add ``equinox`` and ``jaxtyping`` as dependencies and converts the ``QuadratureRule`` ``namedtuple`` implementation to a ``equinox.Module``. ``jaxtyping`` just helps document stuff better. It serves no functional purpose other than that.

@ralberd I ran that hole array problem you sent me ~10 times for each implementation and so no real difference.

**Review by ralberd — APPROVED** [review]

**Review by btalamini — APPROVED** [review]
This looks really useful! Thanks, Craig!

**Comment by cmhamel** [comment]
@ralberd @btalamini @tupek2 

If it's ok with y'all, I can tag the main branch prior to merging this as say "v0.0.1" or "pre-equinox" so if we need to easily revert to pre-equinox stuff it should be fairly straightforward

**Comment by btalamini** [comment]
> @ralberd @btalamini @tupek2
> 
> If it's ok with y'all, I can tag the main branch prior to merging this as say "v0.0.1" or "pre-equinox" so if we need to easily revert to pre-equinox stuff it should be fairly straightforward

That's a good suggestion. Go for it.

**Pull request merged**
